runtime: python39
service: default
entrypoint: gunicorn -b :$PORT main:app --log-level debug

instance_class: F1

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10

env_variables:
  FLASK_APP: "main"
  FLASK_ENV: "production"
  FLASK_DEBUG: "0"
  DATABASE_URL: "sqlite:////tmp/users.db"
  SECRET_KEY: "tu-clave-secreta-aqui-cambiame-en-produccion"
  ALLOWED_ORIGINS: "https://frontend-dot-proyeckev.uc.r.appspot.com"

handlers:
- url: /.*
  script: auto 
  secure: always 